FROM gar-registry.caas.intel.com/virtiot/vaapi-dxg:base
#FROM openvino/ubuntu20_data_dev:2021.4.2
#FROM dlstreamer/dlstreamer:latest

USER root

## Openvino Installation
RUN apt install -y curl gpg-agent software-properties-common
RUN curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | apt-key add -
RUN echo "deb https://apt.repos.intel.com/openvino/2022 `. /etc/os-release && echo ${UBUNTU_CODENAME}` main" | tee /etc/apt/sources.list.d/intel-openvino-2022.list
RUN apt update && apt install -y openvino-libraries-dev-2022.1.0 \
openvino-samples-2022.1.0 libopenvino-python-2022.1.0 \
openvino-opencv

RUN source /opt/intel/openvino_2022/setupvars.sh && \
/opt/intel/openvino_2022/install_dependencies/install_NEO_OCL_driver.sh -y
#RUN apt update && apt install -y intel-dlstreamer-dev
#RUN /opt/intel/dlstreamer/install_dependencies/install_media_driver.sh -y

RUN source /opt/intel/openvino_2022/setupvars.sh && \
python3 -m pip install --upgrade pip && \
python3 -m pip install --ignore-installed openvino-dev

## Dlstreamer dependencies
RUN apt install -y --no-install-recommends  cmake build-essential libpython3-dev python-gi-dev
#RUN apt install -y --no-install-recommends intel-dlstreamer-gst cmake build-essential libpython3-dev python-gi-dev

## Dlstreamer Python requirements
RUN git clone https://github.com/dlstreamer/dlstreamer.git ~/dlstreamer_gst && \
cd ~/dlstreamer_gst && \
source /opt/intel/openvino_2022/setupvars.sh && \
python3 -m pip install --upgrade pip && \
python3 -m pip install -r requirements.txt


## OpenCL
RUN apt install -y wget
RUN mkdir /root/neo && cd /root/neo && \
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.11485/intel-igc-core_1.0.11485_amd64.deb && \
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.11485/intel-igc-opencl_1.0.11485_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/22.27.23681/intel-level-zero-gpu-dbgsym_1.3.23681_amd64.ddeb && \
wget https://github.com/intel/compute-runtime/releases/download/22.27.23681/intel-level-zero-gpu_1.3.23681_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/22.27.23681/intel-opencl-icd-dbgsym_22.27.23681_amd64.ddeb && \
wget https://github.com/intel/compute-runtime/releases/download/22.27.23681/intel-opencl-icd_22.27.23681_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/22.27.23681/libigdgmm12_22.1.3_amd64.deb && \
wget https://github.com/intel/compute-runtime/releases/download/22.27.23681/ww27.sum && sha256sum -c ww27.sum && \
dpkg -i *.deb
RUN curl -sSL https://repositories.intel.com/graphics/intel-graphics.key | apt-key add - && \
apt-add-repository 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main' && \
apt update && apt install -y intel-opencl-icd


## Install Intel® oneAPI DPC++/C++ Compiler
RUN curl -sSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | apt-key add - && \
add-apt-repository "deb https://apt.repos.intel.com/oneapi all main" && \
apt update && apt install -y intel-oneapi-compiler-dpcpp-cpp intel-level-zero-gpu level-zero-dev


RUN source /opt/intel/openvino_2022/setupvars.sh && \
source /opt/intel/oneapi/compiler/latest/env/vars.sh && \
mkdir ~/dlstreamer_gst/build && \
cd ~/dlstreamer_gst/build && \
cmake \
-DCMAKE_INSTALL_PREFIX=/opt/intel/dlstreamer \
-DCMAKE_BUILD_TYPE=Debug .. \
-DENABLE_VAAPI=ON \
&& \
make -j$(nproc) && make install && ldconfig 
#source /opt/intel/dlstreamer/gstreamer/setupvars.sh && \



